language: csharp
solution: Red.Wine.sln
install:
  - mono nuget.exe restore Red.Wine.sln
script:
  - msbuild /p:Configuration=Release Red.Wine.sln
  - mono nuget.exe -v
  - mono nuget.exe update -self
  - mono nuget.exe -v
  - mono nuget.exe pack ./Red.Wine/Red.Wine.csproj -Version $MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER
  - mono nuget.exe setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE -Verbosity quiet
  - mono nuget.exe push Red.Wine.$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER.nupkg -Source $NUGET_SOURCE