language: csharp
solution: Red.Wine.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
   - mono .nuget/nuget.exe restore Red.Wine.sln -Verbosity detailed
script:
  - msbuild /p:Configuration=Release Red.Wine.sln
  - mono .nuget/nuget.exe update -self
  - mono .nuget/nuget.exe # Output NuGet's version number
  - mono .nuget/nuget.exe pack ./Red.Wine/Red.Wine.csproj -Version $MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER
  - mono .nuget/nuget.exe setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE -Verbosity quiet
  - mono .nuget/nuget.exe push Red.Wine.$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER.nupkg -Source $NUGET_SOURCE